### PR TITLE
Exemple config file

### PR DESCRIPTION
**Pull request by ferazambuja**
To make it easier.

### CODE REVIEW

**Comment by Cy4n1d3** [comment]
This needs to be updated - if the api key is set, it must be valid!

**Comment by ferazambuja** [comment]
Yeah maybe we do the route of Python spawn_locations.py Lat Lon -k API key. 
I just feel that a lot of people have no idea and get nothing showing on their maps.

**Comment by Cy4n1d3** [comment]
Just insert the default API key into the JSON and update the README to notify people of problems that can occur using the default one.

**Comment by Cy4n1d3** [comment]
I'll merge this in and work around it inside the code...

**Pull request merged**
