### PR TITLE
UTF-8 Work around/#poke_id ignored

### PR DESCRIPTION
**Pull request by ferazambuja**
poke_id = "#{:03} {}".format(t[2]['id'], pokemonsJSON[str(t[2]['id'])])
Couldn't find a way to encode this one.

### CODE REVIEW

**Comment by Cy4n1d3** [comment]
I don't like the `encode()` workaround.
Essentially it breaks correct display of Pokemon names on html pages, i.e. `Nidoran♂` becomes `Nidoranâ™` :\

**Comment by ferazambuja** [comment]
Yes, It does. I wonder how the other maps deal with. Some just show (f) (m).
The python documentations says that reads json as utf-8. The way I'm forcing the encode is probably an overkill, must be a way to encode once.

**Comment by Cy4n1d3** [comment]
JSON uses UTF-8 encoding by default, thus it should be handled like that by the parser (in this case Python).
If this project is going to be expanded further, the code itself might need some refactoring too, as it's not quite following OOP principles right now :)

**Comment by ferazambuja** [comment]
Me too. I feel that some tweaking on the report feature inside the own pokeminer might be best.
The HTML files lacked the utf-8 declaration.

**Pull request closed without merging**
